* emacs-tut : opinionated emacs tutorial in three acts

1) [[file:emacs-primer.org]] : In Finnish, my personal view how emacs
   keybings should be presented - TL;DR; C-g and C-h are the only keys
   you need to know ;)
2) [[file:org-primer.org]] : Primer helping to understand emacs and
   org-mode. Includes some examples. This is *NOT* the way to
   configure emacs - it is intended to help in understanding workings
   of emacs, and especially, of org-mode.
3) [[file:emacs-admin.org]] : The first version for your own emacs
   configuration to "tangle" =~/.emacs.d/init.el= (this file should be
   expanded as your understanding of the capabilieties of emacs
   -ecosystem increases).

*To start*

Run
#+begin_example
git clone https://github.com/jarjuk/emacs-tut
#+end_example

and change the working directory

#+begin_example
cd emacs-tut
#+end_example


*Notice*

~org-primer.org~ should be run using empty emacs setup (= without
=~/.emacs.d/init.el=, =~/.emacs= etc. configuration). This can be done
running

#+begin_example
emacs -q -l demo-init.el org-primer.org
#+end_example

or simply using associated script

#+begin_example
./org-primer.sh
#+end_example>

or even in a cleaner environment (=empty ~tmp~ directory)

#+begin_example
./org-primer.sh --cleanup
#+end_example>
